import { BookingRequest } from "./types";

const today = new Date();
const isoDate = (offset: number) => {
  const date = new Date(today);
  date.setDate(today.getDate() + offset);
  return date.toISOString().slice(0, 10);
};

export const mockRequests: BookingRequest[] = [
  {
    id: "REQ-1048",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    confirmedAt: "",
    cancelledAt: "",
    date: isoDate(1),
    time: "18:00",
    duration: 120,
    format: "half",
    sector: "A+B",
    price: 36000,
    listPrice: 36000,
    salePrice: 36000,
    name: "Алексей Морозов",
    phone: "+7 924 555-18-22",
    team: "Восток",
    source: "Сайт",
    sourceDetail: "",
    status: "new",
    paymentStatus: "deposit",
    prepayment: 2000,
    balance: 34000,
    paymentMethod: "Перевод",
    paymentRecipient: "Не выбран",
    paidAt: "",
    comment: "Нужны два мяча и манишки",
    deletedAt: "",
    payments: [
      {
        id: "PAY-1048-1",
        amount: 2000,
        date: isoDate(0),
        method: "Перевод",
        recipient: "Не выбран",
      },
    ],
  },
  {
    id: "REQ-1047",
    createdAt: new Date(Date.now() - 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 1800000).toISOString(),
    confirmedAt: new Date(Date.now() - 1800000).toISOString(),
    cancelledAt: "",
    date: isoDate(2),
    time: "20:00",
    duration: 60,
    format: "full",
    sector: "A+B+C+D",
    price: 30000,
    listPrice: 30000,
    salePrice: 30000,
    name: "Илья Соколов",
    phone: "+7 914 302-41-90",
    team: "Порт",
    source: "Сайт",
    sourceDetail: "",
    status: "confirmed",
    paymentStatus: "paid",
    prepayment: 10000,
    balance: 20000,
    paymentMethod: "Карта",
    paymentRecipient: "Не выбран",
    paidAt: "",
    comment: "",
    deletedAt: "",
    payments: [
      {
        id: "PAY-1047-1",
        amount: 30000,
        date: isoDate(0),
        method: "Карта",
        recipient: "Не выбран",
      },
    ],
  },
  {
    id: "REQ-1046",
    createdAt: new Date(Date.now() - 7200000).toISOString(),
    updatedAt: new Date(Date.now() - 7200000).toISOString(),
    confirmedAt: "",
    cancelledAt: "",
    date: isoDate(3),
    time: "17:00",
    duration: 60,
    format: "quarter",
    sector: "D",
    price: 10000,
    listPrice: 10000,
    salePrice: 10000,
    name: "Мария Ким",
    phone: "+7 999 120-08-14",
    team: "Спутник",
    source: "Сайт",
    sourceDetail: "",
    status: "new",
    paymentStatus: "unpaid",
    prepayment: 0,
    balance: 10000,
    paymentMethod: "Не выбран",
    paymentRecipient: "Не выбран",
    paidAt: "",
    comment: "Перезвонить после 15:00",
    deletedAt: "",
    payments: [],
  },
];
